apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: git-push-triggerbinding
spec:
  params:
    - name: repo-url
      value: "$(body.repository.clone_url)"
    - name: repo-revision
      value: "$(body.ref)"
